package pkg;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author StylishDheeru
 */
public class Paymentmethods extends javax.swing.JFrame {

    /**
     * Creates new form Paymentmethods
     */
    public Paymentmethods() {
        initComponents();
        setExtendedState(Paymentmethods.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtmobile = new javax.swing.JTextField();
        jtxtPaytm = new javax.swing.JTextField();
        jtxtcvv = new javax.swing.JTextField();
        jtxtdbcamount = new javax.swing.JTextField();
        jbtnaddpaytm = new javax.swing.JButton();
        jbtnadddbc = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxtcardNumber = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Paytm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Debit Card");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Mobile :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Enter Amount :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("CVV :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Enter Amount :");

        jtxtmobile.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jtxtmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtmobileActionPerformed(evt);
            }
        });
        jtxtmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtmobileKeyTyped(evt);
            }
        });

        jtxtPaytm.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jtxtPaytm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPaytmActionPerformed(evt);
            }
        });
        jtxtPaytm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPaytmKeyTyped(evt);
            }
        });

        jtxtcvv.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jtxtcvv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcvvKeyTyped(evt);
            }
        });

        jtxtdbcamount.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jtxtdbcamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdbcamountActionPerformed(evt);
            }
        });
        jtxtdbcamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtdbcamountKeyTyped(evt);
            }
        });

        jbtnaddpaytm.setBackground(new java.awt.Color(255, 255, 0));
        jbtnaddpaytm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnaddpaytm.setText("Add Money");
        jbtnaddpaytm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddpaytmActionPerformed(evt);
            }
        });

        jbtnadddbc.setBackground(new java.awt.Color(255, 255, 0));
        jbtnadddbc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnadddbc.setText("Add Money");
        jbtnadddbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnadddbcActionPerformed(evt);
            }
        });

        jbtnBack.setBackground(new java.awt.Color(255, 255, 0));
        jbtnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnBack.setText("Back");
        jbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Card Number :");

        jtxtcardNumber.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jtxtcardNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcardNumberKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jbtnaddpaytm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(421, 421, 421)
                        .addComponent(jbtnadddbc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtmobile, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jtxtPaytm, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtdbcamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtcvv)
                            .addComponent(jtxtcardNumber))))
                .addGap(180, 180, 180))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtcvv, jtxtdbcamount, jtxtmobile});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnBack, jbtnadddbc, jbtnaddpaytm});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jtxtcardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtcvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jtxtdbcamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnaddpaytm)
                            .addComponent(jbtnadddbc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnBack))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jtxtPaytm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jtxtPaytm, jtxtcardNumber, jtxtcvv, jtxtdbcamount, jtxtmobile});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnBack, jbtnaddpaytm});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jLabel7});

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtmobileActionPerformed

    private void jbtnadddbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnadddbcActionPerformed
             String cvv = jtxtcvv.getText();
             String card = jtxtcardNumber.getText();
             String mon = jtxtdbcamount.getText();
             String user = UserName.user;
             if(jtxtcvv.getText().length() != 3){
                 JOptionPane.showMessageDialog(null, "Please enter valid CVV");
             }
            
                int mon1;
            if(cvv.equals("") || card.equals("") || mon.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter all details to proceed");
            }
            
            else{
                try{
                  
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/oop","root","root");
                Statement stmt=con.createStatement();
                String query = "Select money from login where userid='"+user+"';";
             
                  
                    ResultSet m=stmt.executeQuery(query);
                    
                    m.next();
                      
                    mon1=m.getInt("money");
                      
                    mon1 = mon1+Integer.parseInt(mon);
                    
                      
                query = "Update login set money="+mon1+" where userid='"+user+"';";
                stmt.executeUpdate(query);
                  
                con.close();
                  
                stmt.close();
                    JOptionPane.showMessageDialog(null,"Amount of "+mon+" has been added to your account successfully");
                    jtxtdbcamount.setText(null);
               
                }catch (Exception e){
                    System.out.println("Exception is there ");
                }
            }    
           
    }//GEN-LAST:event_jbtnadddbcActionPerformed

    private void jbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackActionPerformed
        // TODO add your handling code here:
        new Wallet().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnBackActionPerformed

    private void jbtnaddpaytmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddpaytmActionPerformed
            // TODO add your handling code here:
            String mon = jtxtPaytm.getText();
             String mob = jtxtmobile.getText();
             String user = UserName.user;
             //System.out.println(user);
                int mon1;
                if(mon.equals("") || mob.equals("")){
                    JOptionPane.showMessageDialog(null, "Please enter all details to proceed");
                }
           else{
                try{
                  
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/oop","root","root");
                Statement stmt=con.createStatement();
                String query = "Select money from login where userid='"+user+"';";
             
                  
                    ResultSet m=stmt.executeQuery(query);
                    
                    m.next();
                      
                    mon1=m.getInt("money");
                      
                    mon1 = mon1+Integer.parseInt(mon);
                    
                      
                query = "Update login set money="+mon1+" where userid='"+user+"';";
                stmt.executeUpdate(query);
                  
                con.close();
                  
                stmt.close();
                
               JOptionPane.showMessageDialog(null,"Amount of "+mon+" has been added to your account successfully");
               jtxtPaytm.setText(null);
                }catch (Exception e){
                    System.out.println("Exception is there rey");
                }
            }    
            
    }//GEN-LAST:event_jbtnaddpaytmActionPerformed

    private void jtxtPaytmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPaytmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPaytmActionPerformed

    private void jtxtdbcamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdbcamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdbcamountActionPerformed

    private void jtxtcardNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcardNumberKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }
    }//GEN-LAST:event_jtxtcardNumberKeyTyped

    private void jtxtcvvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcvvKeyTyped
       char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }
    }//GEN-LAST:event_jtxtcvvKeyTyped

    private void jtxtmobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtmobileKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }
    }//GEN-LAST:event_jtxtmobileKeyTyped

    private void jtxtPaytmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPaytmKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();}
    }//GEN-LAST:event_jtxtPaytmKeyTyped

    private void jtxtdbcamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdbcamountKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();}
    }//GEN-LAST:event_jtxtdbcamountKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paymentmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paymentmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paymentmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paymentmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paymentmethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnadddbc;
    private javax.swing.JButton jbtnaddpaytm;
    private javax.swing.JTextField jtxtPaytm;
    private javax.swing.JTextField jtxtcardNumber;
    private javax.swing.JTextField jtxtcvv;
    private javax.swing.JTextField jtxtdbcamount;
    private javax.swing.JTextField jtxtmobile;
    // End of variables declaration//GEN-END:variables
}
