package pkg;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//import com.sun.glass.events.KeyEvent;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author StylishDheeru
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        setExtendedState(Registration.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblUsername = new javax.swing.JLabel();
        jlblUserID = new javax.swing.JLabel();
        jlblPwd = new javax.swing.JLabel();
        jlblMbl = new javax.swing.JLabel();
        jlblEmailID = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jbtnAldysgndup = new javax.swing.JButton();
        jtxtMbl = new javax.swing.JTextField();
        jtxtEmailID = new javax.swing.JTextField();
        jbtnCreateUser = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jbtnAldysgndup2 = new javax.swing.JButton();
        jbtnCreateUser2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtnCreateUser3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtmaabil = new javax.swing.JTextField();
        jtxtyeemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Registration");
        setPreferredSize(new java.awt.Dimension(1102, 842));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1102, 842));

        jlblUsername.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jlblUsername.setForeground(new java.awt.Color(255, 255, 0));
        jlblUsername.setText("Username");

        jlblUserID.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jlblUserID.setForeground(new java.awt.Color(255, 255, 0));
        jlblUserID.setText("User ID");

        jlblPwd.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jlblPwd.setForeground(new java.awt.Color(255, 255, 0));
        jlblPwd.setText("Password");

        jlblMbl.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jlblMbl.setForeground(new java.awt.Color(255, 255, 0));
        jlblMbl.setText("Mobile");

        jlblEmailID.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jlblEmailID.setForeground(new java.awt.Color(255, 255, 0));
        jlblEmailID.setText("E-mail ID");

        jtxtUsername.setFont(new java.awt.Font("3ds", 0, 20)); // NOI18N
        jtxtUsername.setPreferredSize(new java.awt.Dimension(7, 27));
        jtxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsernameActionPerformed(evt);
            }
        });

        jtxtUserID.setFont(new java.awt.Font("3ds", 0, 20)); // NOI18N
        jtxtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserIDActionPerformed(evt);
            }
        });

        jbtnAldysgndup.setBackground(new java.awt.Color(255, 255, 0));
        jbtnAldysgndup.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnAldysgndup.setText("Already signed up?");
        jbtnAldysgndup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAldysgndupActionPerformed(evt);
            }
        });

        jtxtMbl.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        jtxtEmailID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jbtnCreateUser.setBackground(new java.awt.Color(255, 255, 0));
        jbtnCreateUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnCreateUser.setText("Create User");
        jbtnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateUserActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("3ds", 0, 20)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Re-enter Password");

        jPasswordField2.setFont(new java.awt.Font("3ds", 0, 20)); // NOI18N
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        jbtnAldysgndup2.setBackground(new java.awt.Color(255, 255, 0));
        jbtnAldysgndup2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnAldysgndup2.setText("Already signed up?");
        jbtnAldysgndup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAldysgndup2ActionPerformed(evt);
            }
        });

        jbtnCreateUser2.setBackground(new java.awt.Color(255, 255, 0));
        jbtnCreateUser2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnCreateUser2.setText("Create User");
        jbtnCreateUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateUser2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Create User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnCreateUser3.setBackground(new java.awt.Color(255, 255, 0));
        jbtnCreateUser3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtnCreateUser3.setText("Create User");
        jbtnCreateUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateUser3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Mobile ");

        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("E-mail");

        jtxtmaabil.setFont(new java.awt.Font("3ds", 0, 20)); // NOI18N
        jtxtmaabil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtmaabilKeyTyped(evt);
            }
        });

        jtxtyeemail.setFont(new java.awt.Font("3ds", 0, 20)); // NOI18N

        jLabel5.setText("jLabel5");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("TAXIWALA Inc.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnCreateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(115, 115, 115)
                        .addComponent(jbtnAldysgndup)
                        .addGap(1007, 1007, 1007))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnCreateUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1279, 1279, 1279))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtEmailID)
                            .addComponent(jbtnAldysgndup2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlblUserID)
                                        .addComponent(jlblPwd)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4))
                                    .addGap(273, 273, 273))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlblUsername)
                                    .addGap(2, 2, 2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6))
                            .addComponent(jtxtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtyeemail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtmaabil, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtUserID, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(666, 666, 666)
                        .addComponent(jtxtMbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlblMbl)
                                .addComponent(jlblEmailID)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(jLabel3))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(357, 357, 357)
                    .addComponent(jbtnCreateUser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(1269, 1269, 1269)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtxtEmailID, jtxtMbl, jtxtUserID, jtxtUsername});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jbtnAldysgndup2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblUsername)
                            .addComponent(jtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblUserID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtmaabil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtyeemail, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jbtnAldysgndup2))
                        .addGap(96, 96, 96)
                        .addComponent(jLabel6)
                        .addGap(478, 478, 478)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblMbl))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblEmailID)
                    .addComponent(jtxtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAldysgndup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jbtnCreateUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(1338, Short.MAX_VALUE)
                    .addComponent(jbtnCreateUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(97, 97, 97)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jtxtEmailID, jtxtMbl});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jbtnAldysgndup2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCreateUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateUser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCreateUser3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String v1= jtxtUserID.getText();
        String v2= jPasswordField1.getText();
        String v6 = jPasswordField2.getText();
        String v3 = jtxtUsername.getText();
        String v4 = jtxtyeemail.getText();
        String v5 = jtxtmaabil.getText();
        if(v1.equals("") || v2.equals("")||v3.equals("")||v4.equals("")||v5.equals("")||v6.equals("")){
                JOptionPane.showMessageDialog(null, "Fill all details to register");
        }
        
        else{

        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/oop","root","root");
            Statement stmt=con.createStatement();
            if(v6.equals(v2))
            {
                String query="insert into login values('"+v1+"','"+v2+"','"+v3+"','"+v4+"','"+v5+"',0,0);";
                int m=stmt.executeUpdate(query);
                stmt.close();
                con.close();
                JOptionPane.showMessageDialog(null,"Successfully Registered");
                new Front_page().setVisible(true);
                this.dispose();
            }
            else
            {JOptionPane.showMessageDialog(null,"Please re-enter password");}}
        catch (Exception e)
        {JOptionPane.showMessageDialog(null,"error in username or password");}        // TODO add your handling code here:
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnCreateUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCreateUser2ActionPerformed

    private void jbtnAldysgndup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAldysgndup2ActionPerformed
        // TODO add your handling code here:
        new Front_page().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnAldysgndup2ActionPerformed

    private void jbtnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateUserActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:

    }//GEN-LAST:event_jbtnCreateUserActionPerformed

    private void jbtnAldysgndupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAldysgndupActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jbtnAldysgndupActionPerformed

    private void jtxtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserIDActionPerformed

    private void jtxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsernameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jtxtmaabilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtmaabilKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == java.awt.event.KeyEvent.VK_BACK_SPACE) ||
         (c == java.awt.event.KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }
    }//GEN-LAST:event_jtxtmaabilKeyTyped

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JButton jbtnAldysgndup;
    private javax.swing.JButton jbtnAldysgndup2;
    private javax.swing.JButton jbtnCreateUser;
    private javax.swing.JButton jbtnCreateUser2;
    private javax.swing.JButton jbtnCreateUser3;
    private javax.swing.JLabel jlblEmailID;
    private javax.swing.JLabel jlblMbl;
    private javax.swing.JLabel jlblPwd;
    private javax.swing.JLabel jlblUserID;
    private javax.swing.JLabel jlblUsername;
    private javax.swing.JTextField jtxtEmailID;
    private javax.swing.JTextField jtxtMbl;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtUsername;
    private javax.swing.JTextField jtxtmaabil;
    private javax.swing.JTextField jtxtyeemail;
    // End of variables declaration//GEN-END:variables
}
